[package]
org = "sameera"
name = "ternal_relationships"
version = "0.1.0"
distribution = "2201.9.0"

[build-options]
observabilityIncluded = true

[[tool.persist]]
id = "generate-db-client"
targetModule = "frankqs.db"
options.datastore = "mysql"
filePath = "persist/model.bal"

[[platform.java17.dependency]]
groupId = "io.ballerina.stdlib"
artifactId = "persist.sql-native"
version = "1.3.0"

