servicePort = 8081

## Database connection options
host = "localhost"
port = 3306
user = "order_biblio_user"
password = "most_secure_password123"
database = "order_biblio_database"

[connectionOptions.ssl]
allowPublicKeyRetrieval=true

